### ISSUE TITLE
progen generate -f projects.yaml -p lpc55s69_mculink_if -t uvision, problem!

### ISSUE THREAD

**Issue by fabio-ric-silva** [project-generator/project_generator_definitions#158]
When tried creating the uVision project, I had an error:

```
 Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fabio.silva\AppData\Local\Programs\Python\Python313\Scripts\progen.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\fabio.silva\AppData\Local\Programs\Python\Python313\Lib\site-packages\project_generator\__main__.py", line 67, in main
    return args.func(args)
           ~~~~~~~~~^^^^^^
  File "C:\Users\fabio.silva\AppData\Local\Programs\Python\Python313\Lib\site-packages\project_generator\commands\generate.py", line 70, in run
    build_failed, export_failed = r.get(timeout=20.0)
                                  ~~~~~^^^^^^^^^^^^^^
  File "C:\Users\fabio.silva\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
RuntimeError: Target cortex-m33 is not supported. Please add them to https://github.com/project-generator/project_generator_definitions
```

I tried to create another projects using this processor, but, every time the same error!

Someone, please, could help me to figure out this problem?

**Comment by toyowata** [comment]
Hi,

You can probably modify the lpc55s69.yaml file to add uvision specific part
```
tool_specific:
    uvision:
        TargetOption:
```

 https://github.com/project-generator/project_generator_definitions/blob/master/project_generator_definitions/mcu/nxp/lpc55s69.yaml

How to add:
https://github.com/project-generator/project_generator_definitions/tree/master?tab=readme-ov-file#uvision

**Comment by 0xc0170** [comment]
Thanks @toyowata for helping.

@fabio-ric-silva The error message might not be clear in this case, definitions is not found, it has to be added for uvision to be able to generate a valid project.

**Comment by 0xc0170** [comment]
I close this as resolved.
